# Site settings
title: Brandy Horne - Data Scientist
description: >
  Data scientist with a passion for clarity, strategy, and storytelling. Expert in time series, survival analysis, regression modeling, and translating data into business impact.
baseurl: "" 
url: "https://brandyanalytics.github.io" # Replace with your actual GitHub Pages URL
theme: jekyll-theme-minimal


